src/MonEtab2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls')),
    path('user/', include('user.urls')),
    path('teacher/', include('teacher.urls')),
    path('student/', include('student.urls')),
    path('school/', include('school.urls')),
    path('report/', include('report.urls')),
    path('address/', include('base.urls.adress_urls')),
    path('rapport/', include('report.urls')),
    path('api/', include('api.urls')),
]

src/api/urls.py
from django.urls import path
from api.apiviews import student_apiviews
from api.apiviews.student_apiviews import student_list

urlpatterns = [
    path('', student_list),
]

src/teacher/urls.py
from django.urls import path

from teacher.views import list_teachers, create_teacher, update_teacher, delete_teacher

app_name = 'teacher'
urlpatterns = [
    path('', list_teachers, name='list-teachers'),
    path('create_teacher/', create_teacher, name='create-teacher'),
    path('update_teacher/<int:id>', update_teacher, name='update-teacher'),
    path('delete_teacher/<int:id>', delete_teacher, name='delete-teacher'),
]

src/teacher/models.py
'''from django.db import models
from base.models.person_models import Person
# Create your models here.


class Teacher(Person):
    available = models.BooleanField(default=True)
    specialty = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name} - {self.specialty}"
'''

src/teacher/models/teacher_model.py
from django.db import models

from base.models.person_model import PersonModel


class TeacherModel(PersonModel):
    available = models.BooleanField(default=True)
    specialty = models.CharField(max_length=255)

src/teacher/forms/teacher_forms.py
from django import forms
from teacher.models.teacher_model import TeacherModel


class TeacherForm(forms.ModelForm):
    class Meta:
        model = TeacherModel
        exclude = ['status',]

        widgets = {
            'birthday': forms.DateInput(attrs={'type': 'date'})
        }

src/teacher/views.py
from django.shortcuts import render, redirect
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from teacher.models.teacher_model import TeacherModel
from teacher.forms.teacher_forms import TeacherForm
from user.models.user_model import UserModel


#from user.forms.user_form import UserForm


# Create your views here.
@login_required(login_url='dashboard:sign_in')
def list_teachers(request):
    teacher = TeacherModel.objects.filter(status=True)

    context = {
        'teachers': teacher
    }
    return render(request, "listTeacher.html", context)

@login_required(login_url='dashboard:sign_in')
def create_teacher(request):
    context = {
        'title': 'Ajouter un Professeur',
        'submit_value': 'Ajouter',
        'h1': 'Nouveau Professeur',
    }

    if request.method == 'POST':
        form = TeacherForm(request.POST)
        if form.is_valid():
            #teacher = form.save(commit=False)
            form.save()
            messages.success(request, 'Le professeur a été ajouté avec succès.')
            return redirect('teacher:list-teachers')
        else:
            print(form.errors)
    else:
        form = TeacherForm()
        # user_form = UserForm()
    context['form'] = form
    # context['forms'] = user_form

    return render(request, "formsTeacher.html", context)

@login_required(login_url='dashboard:sign_in')
def update_teacher(request, id):
    teacher = TeacherModel.objects.get(id=id)
    # user = get_object_or_404(UserModel, teacher=teacher)
    context = {
        'title': 'Modifier le professeur',
        'submit_value': 'Modifier',
        'h1': 'Modifier Professeur',
    }
    if request.method == "POST":
        form = TeacherForm(request.POST, instance=teacher)
        # user_form = UserForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            # user_form.save()
            return redirect("teacher:list-teacher")
        else:
            messages.error(request, "Erreur dans le formulaire. Veuillez vérifier les champs.")

    form = TeacherForm(instance=teacher)
    # user_form = UserForm(instance=user)
    context['form'] = form
    # context['forms'] = user_form

    return render(request, "formsTeacher.html", context)

@login_required(login_url='dashboard:sign_in')
def delete_teacher(request, id):
    teacher = get_object_or_404(TeacherModel, id=id)
    # teacher.delete()
    # user = get_object_or_404(UserModel, teacher=teacher)
    teacher.status = False
    teacher.active = False
    teacher.save()
    # user.is_active = False
    # user.save()
    return redirect('teacher:list-teacher')

src/teacher/templates/formsTeacher.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<form method="POST">
    {% csrf_token %}
    {{ form }}
    <div>
        <button type="submit">Enregistrer</button>
    </div>
</form>

</body>
</html>

src/teacher/templates/listTeacher.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Subject Management</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link rel="stylesheet" href="">
</head>
<body>
    <div class="container-fluid">
        <div class="row vh-100">

            {% include 'Menu.html' %}


            <div class="col-md-10 content">

                <div class="header bg-info text-white d-flex justify-content-between align-items-center p-3">
                    <span>"Vivez comme si vous deviez mourir demain. Apprenez comme si vous deviez vivre éternellement."</span>
                    <div class="user-info d-flex align-items-center">
                        <span>admin</span>
                        <img src="image/images.png" alt="User Icon" class="rounded-circle ml-2" width="30">
                    </div>
                </div>


                <div class="d-flex justify-content-between align-items-center my-3 px-4">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="#"><i class="fas fa-tachometer-alt"></i> Dashboard</a></li>
                            <li class="breadcrumb-item active" aria-current="page">User</li>
                        </ol>
                    </nav>
                  <button class="btn btn-info"><a href="{% url 'teacher:create-teacher' %}"><i class="fas fa-plus-circle"></i></a> Create User</button>
                </div>


                <div class="card m-4 p-4">
                    <h3>SUBJECT</h3>
                    <div class="d-flex justify-content-between align-items-center mb-3">
                        <div class="form-group">
                            <label for="classSelect">Select Class Name:</label>
                            <select id="classSelect" class="form-control">
                                <option>affiche 25</option>
                                <option>affiche 35</option>
                                <option>affiche 65</option>
                                <option>tout</option>

                            </select>
                        </div>
                        <input type="text" class="form-control w-25" placeholder="Search...">
                    </div>


                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Nom</th>
                                <th>Prenom</th>
                                <th>Numero</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for teacher in teachers %}
                            <tr>
                                <td>1</td>
                                <td>{{ teacher.first_name }}</td>
                                <td>{{ teacher.last_name }}</td>
                                <td>{{ teacher.phone_number }}</td>

                                <td>
                                    <a href="#" class="text-success"><i class="fas fa-edit"></i></a>
                                    <a href="#" class="text-danger ml-2"><i class="fas fa-trash"></i></a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>