src/MonEtab2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls')),
    path('user/', include('user.urls')),
    path('teacher/', include('teacher.urls')),
    path('student/', include('student.urls')),
    path('school/', include('school.urls')),
    path('report/', include('report.urls')),
    path('address/', include('base.urls.adress_urls')),
    path('rapport/', include('report.urls')),
    path('api/', include('api.urls')),
]

src/api/urls.py
from django.urls import path
from api.apiviews import student_apiviews
from api.apiviews.student_apiviews import student_list

urlpatterns = [
    path('', student_list),
]

src/dashboard/urls.py
from django.urls import path
from dashboard.views import index
from user.views.user_views import connexion, disconnect


app_name = 'dashboard'
urlpatterns = [
    path('', index, name='index'),
    path('sign_in/', connexion, name='sign_in'),
    path('logout/', disconnect, name='logout'),
]

src/dashboard/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render


# Create your views here.


@login_required(login_url='dashboard:sign_in')
def index(request):
    return render(request, 'dashboard.html')

src/dashboard/templates/connexion/connexion.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Sign Up Form by Colorlib</title>

    <!-- Font Icon -->
    <link rel="stylesheet" href="fonts/material-icon/css/material-design-iconic-font.min.css">

    <!-- Main css -->
    <link rel="stylesheet" href="css/style.css">
</head>
<body>

    <div class="main">
        <!-- Sing in  Form -->
        <section class="sign-in">
            <div class="container">
                <div class="signin-content">
                    <div class="signin-image">
                        <figure><img src="images/signin-image.jpg" alt="sing up image"></figure>
                        <a href="#" class="signup-image-link">Create an account</a>
                    </div>

                    <div class="signin-form">
                        <h2 class="form-title">Sign-In</h2>
                        <form method="POST" class="register-form" id="login-form">
                            {% csrf_token %}
                            <input type="text" name="username" id="name" placeholder="Your Name"/>
                            <input type="password" name="Password" id="pass" placeholder="Password"/>

                            <div class="form-group form-button">
                                <button type="submit" name="signin" id="signin" class="form-submit">Se connecter</button>
                            </div>
                           <!-- <div class="form-group">
                                <input type="checkbox" name="remember-me" id="remember-me" class="agree-term" />
                                <label for="remember-me" class="label-agree-term"><span><span></span></span>Remember me</label>
                            </div>
                            <div class="form-group form-button">
                                <input type="submit" href="{% url 'dashboard:index' %}" name="signin" id="signin" class="form-submit" value="Log in"/>
                            </div> -->
                        </form>
                        <div class="social-login">
                            <span class="social-label">Or login with</span>
                            <ul class="socials">
                             <!--   <li><a href="#"><i class="display-flex-center zmdi zmdi-facebook"></i></a></li>
                                <li><a href="#"><i class="display-flex-center zmdi zmdi-twitter"></i></a></li>
                                <li><a href="#"><i class="display-flex-center zmdi zmdi-google"></i></a></li> -->
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </section>

    </div>

    <!-- JS -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="js/main.js"></script>
</body><!-- This templates was made by Colorlib (https://colorlib.com) -->
</html>