src/MonEtab2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls')),
    path('user/', include('user.urls')),
    path('teacher/', include('teacher.urls')),
    path('student/', include('student.urls')),
    path('school/', include('school.urls')),
    path('report/', include('report.urls')),
    path('address/', include('base.urls.adress_urls')),
    path('rapport/', include('report.urls')),
    path('api/', include('api.urls')),
]

src/api/urls.py
from django.urls import path
from api.apiviews import student_apiviews
from api.apiviews.student_apiviews import student_list

urlpatterns = [
    path('', student_list),
]

src/user/urls.py
from django.urls import path, include
from user.views import user_views
from django.urls import path
from user.views.role_user_views import list_role_user , create_role_user, update_role_user, delete_role_user
from user.views.user_views import list_user, create_user, update_user, delete_user
#from user.views.role_user_views import list_role_user, update_role_user, create_role_user, delete_role_user



app_name = 'user_role'
urlpatterns = [
    # urls de users
    path('', list_user, name='list-user'),
    path('create_user/', create_user, name='create-user'),
    path('update_user/', update_user, name='update-user'),
    path('delete_user/', delete_user, name='delete-user'),


    #vues de role
    path('list_role_user/', list_role_user, name='list-role'),
    path('create_role/', create_role_user, name='create-role'),
    path('update_role/', update_role_user, name='update-role'),
    path('delete_role/', delete_role_user, name='delete-role'),
]

src/user/models/role_user_model.py
from django.db import models


class RoleUserModel(models.Model):
    role = models.CharField(max_length=255)
    
    def __str__(self):
        return self.role

src/user/models/user_model.py
from django.db import models
from base.models.helpers.date_time_model import DateTimeModel
from django.contrib.auth.models import AbstractUser


class UserModel(DateTimeModel, AbstractUser):
    school = models.ForeignKey('school.SchoolModel', on_delete=models.CASCADE, null=True)
    role = models.ForeignKey('user.RoleUserModel', on_delete=models.CASCADE, null =True )
    #pseudo = models.CharField(max_length=255)
    #password = models.CharField(max_length=255)

src/user/forms/role_forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from user.models.role_user_model import RoleUserModel
from django import forms


class RoleUserForms(forms.ModelForm):
    class Meta:
        model = RoleUserModel
        fields = ['role']

src/user/forms/user_forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from user.models.user_model import UserModel
from django import forms
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import User


class UserForms(forms.ModelForm):
    class Meta:
        model = UserModel
        fields = ['username', 'email', 'password', 'school', 'role']
        widgets = {
            'password': forms.PasswordInput(),
        }

src/user/views/role_user_views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from user.models.role_user_model import RoleUserModel
from user.forms.role_forms import RoleUserForms

@login_required(login_url='dashboard:sign_in')
def list_role_user(request):
    role = RoleUserModel.objects.all()
    context = {'role': role}
    return render(request, 'role/list.html', context)

@login_required(login_url='dashboard:sign_in')
def create_role_user(request):
    form = RoleUserForms(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect('user_role:list-role')
        else:
            print('erreur')
    context = {'form': form}
    return render(request, 'role/forms.html', context)

@login_required(login_url='dashboard:sign_in')
def update_role_user(request, id):
    role_user = RoleUserModel.objects.get(id=id)
    context = {
        'title': 'Modifier le Rôle de l\'Utilisateur',
        'submit_value': 'Modifier',
        'h1': 'Modifier Rôle Utilisateur',
    }
    if request.method == "POST":
        role_user_form = RoleUserForms(request.POST, instance=role_user)
        if role_user_form.is_valid():
            role_user_form.save()
            return redirect("role_user:list_role_user")
        else:
            messages.error(request, "Erreur dans le formulaire. Veuillez vérifier les champs.")

    role_user_form = RoleUserForms(instance=role_user)
    context['form'] = role_user_form

    return render(request, "role/forms.html", context)

@login_required(login_url='dashboard:sign_in')
def delete_role_user(request, id):
    role_user = get_object_or_404(RoleUserModel, id=id)
    # role_user.delete()
    role_user.status = False
    role_user.save()
    return redirect('role_user:list_role_user')

src/user/views/user_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from django.contrib.auth import login, authenticate, logout
from django.shortcuts import render, redirect
from school.models.school_model import SchoolModel
from school.models.app_settings_model import AppSettingsModel
from user.models import UserModel, RoleUserModel
from user.forms.user_forms import UserForms


# Create your views here.
@login_required(login_url='dashboard:sign_in')
def list_user(request):
    users = UserModel.objects.all()

    number_user = users.count()
    context = {
        'users': users,
        'total': number_user,

    }
    return render(request, "listUser.html", context)


@login_required(login_url='dashboard:sign_in')
def create_user(request):
    if request.method == 'POST':
        password = request.POST.get('password')
        form = UserForms(request.POST)
        if form.is_valid():
            forms = form.save(commit=False)
            forms.set_password(password)
            forms.save()
            return redirect('user_role:list-user')
    roles = RoleUserModel.objects.all()
    print(roles)
    form = UserForms()
    context = {
        'form': form,
        'roles': roles,
    }
    return render(request, 'formUser.html', context)


@login_required(login_url='dashboard:sign_in')
def update_user(request, id):
    pass


@login_required(login_url='dashboard:sign_in')
def delete_user(request, id):
    pass


def connexion(request):
    setting = AppSettingsModel.objects.all()
    school = SchoolModel.objects.all()
    if not setting:
        return redirect('school:setting-create')
    if not school:
        return redirect('school:school-create')

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('Password')
        if not username and not password:
            print(username, password)
            messages.error('Error')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('dashboard:index')
        else:
            return redirect('dashboard:sign_in')
    if request.user.is_authenticated:
        return redirect('dashboard:index')

    return render(request, 'connexion/connexion.html', )


@login_required(login_url='dashboard:sign_in')
def disconnect(request):
    logout(request)
    return redirect('dashboard:sign_in')

src/user/templates/formUser.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Subject Management</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link rel="stylesheet" href="style.css">
    <link rel="stylesheet" href="formUser.html">

</head>
<body>


    <div class="container-fluid">
        <div class="row vh-100">

            {% include 'Menu.html' %}


            <div class="col-md-10 content">
                <div class="header bg-info text-white d-flex justify-content-between align-items-center p-3">
                    <span>"Vivez comme si vous deviez mourir demain. Apprenez comme si vous deviez vivre éternellement."</span>
                    <div class="user-info d-flex align-items-center">
                        <span>admin</span>
                        <img src="image/images.png" alt="User Icon" class="rounded-circle ml-2" width="30">
                    </div>
                </div>

                <section class="dashboard">

                    <form method="post" class="registration-form">
                        {% csrf_token %}
                        {{ form }}
                        <button type="submit" class="btn-submit">S'inscrire</button>
                    </form>

                </section>
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="index.js"></script>
    <!-- Sources for icons -->
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
</body>
</html>

src/user/templates/listUser.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Subject Management</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link rel="stylesheet" href="">
</head>
<body>
    <div class="container-fluid">
        <div class="row vh-100">

            {% include 'Menu.html' %}


            <div class="col-md-10 content">

                <div class="header bg-info text-white d-flex justify-content-between align-items-center p-3">
                    <span>"Vivez comme si vous deviez mourir demain. Apprenez comme si vous deviez vivre éternellement."</span>
                    <div class="user-info d-flex align-items-center">
                        <span>admin</span>
                        <img src="image/images.png" alt="User Icon" class="rounded-circle ml-2" width="30">
                    </div>
                </div>


                <div class="d-flex justify-content-between align-items-center my-3 px-4">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="#"><i class="fas fa-tachometer-alt"></i> Dashboard</a></li>
                            <li class="breadcrumb-item active" aria-current="page">User</li>
                        </ol>
                    </nav>
                  <button class="btn btn-info"><a href="{% url 'user_role:create-user' %}"><i class="fas fa-plus-circle"></i></a> Create User</button>
                </div>


                <div class="card m-4 p-4">
                    <h3>USER</h3>
                    <div class="d-flex justify-content-between align-items-center mb-3">
                        <div class="form-group">
                            <label for="classSelect">Select Class Name:</label>
                            <select id="classSelect" class="form-control">
                                <option>affiche 25</option>
                                <option>affiche 35</option>
                                <option>affiche 65</option>
                                <option>tout</option>

                            </select>
                        </div>
                        <input type="text" class="form-control w-25" placeholder="Search...">
                    </div>


                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Pseudo</th>
                                <th>role</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for users in users %}
                            <tr>
                                <td>1</td>
                                <td>{{ users.pseudo }}</td>
                                <td>{{ users.role }}</td>
                                <td>
                                    <a href="#" class="text-success"><i class="fas fa-edit"></i></a>
                                    <a href="#" class="text-danger ml-2"><i class="fas fa-trash"></i></a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>